// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdTzcTLkTDvJyLaVJCLVDIcTZ-3WCATMg',
    appId: '1:601911078689:web:3418824f446af14f88d860',
    messagingSenderId: '601911078689',
    projectId: 'voyageglid3',
    authDomain: 'voyageglid3.firebaseapp.com',
    storageBucket: 'voyageglid3.appspot.com',
    measurementId: 'G-1ERQSQV751',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOzvzcYUzbWR_n0_UyYCSWbBeZ6w8VzpA',
    appId: '1:601911078689:android:d5bc0e1c42eadfdf88d860',
    messagingSenderId: '601911078689',
    projectId: 'voyageglid3',
    storageBucket: 'voyageglid3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnVUpFCwQ7BLkF-g7-ykUg39Dg2nhVZUo',
    appId: '1:601911078689:ios:4afb1688ddd6e0ba88d860',
    messagingSenderId: '601911078689',
    projectId: 'voyageglid3',
    storageBucket: 'voyageglid3.appspot.com',
    iosClientId: '601911078689-ojbrmvkeocah63a2oc4g0l0jjnt39t5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyage1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnVUpFCwQ7BLkF-g7-ykUg39Dg2nhVZUo',
    appId: '1:601911078689:ios:4afb1688ddd6e0ba88d860',
    messagingSenderId: '601911078689',
    projectId: 'voyageglid3',
    storageBucket: 'voyageglid3.appspot.com',
    iosClientId: '601911078689-ojbrmvkeocah63a2oc4g0l0jjnt39t5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyage1',
  );
}
